#!/usr/bin/env python
import sys,os,shutil,commands
from gap_utils import * 

myname_full = sys.argv[0]
myname = os.path.basename(myname_full)
def f_Help_Info():
  print "\n  "+myname_full + ": a Python script to set some files used for wien2k\n"
  print "  Usage: " + myname + " [options]"\
  + """
  Options:  
    -d               # set the debug mode
    -f <case_name>   # case name 
    -o <obj=inc>     
    -h               # print out this information 
  """
  sys.exit(0)

if f_Getopt('-h',0,False): f_Help_Info()

case_name = f_Getopt('-f',   1, ''    )
obj = f_Getopt('-o',   1, 'inc'    )

case_name = f_Check_Name(case_name    )
nat = f_Get_Natom(case_name)

if obj == 'inc':
  # make a copy of the original file 
  fl_inc = case_name+".inc"
  fl_inc_old = case_name+".inc_old"

  shutil.move(fl_inc,fl_inc_old) 
  ifile = open(fl_inc_old,'r') 
  ofile = open(fl_inc,'w') 

  for i in range(nat):
    line_s = ifile.readline().split()
    norb   = int(line_s[0])
    shift  = float(line_s[1]) 
    ofile.write("%d %3.1f 1   # NUMBER OF ORBITALS (EXCLUDING SPIN), SHIFT, IPRINT\n"%(norb,shift))
    for j in range(norb):
      line = ifile.readline()
      ofile.write(line) 
  ofile.write("0    end switch\n")

  ifile.close()
  ofile.close() 

elif obj == 'int':
  fl_int = case_name+".int"
  if os.path.isfile(fl_int):
    shutil.move(fl_int, fl_int+"_old") 

  ofile = open(fl_int, 'w') 
  ofile.write(case_name + "    # title  \n") 
  ofile.write("-1.500 0.002 2.00 0.011   EMIN, DE, EMAX, Gauss-broadening(>de)\n")
  ofile.write("%d        # NUMBER OF DOS-CASES specified below\n"%(nat + 1))
  ofile.write("0    1   total         atom, case=column in qtl-header, label\n")
  for ia in range(nat):
    ofile.write("%d    1   Atom%d-tot \n"%(ia+1,ia+1))

  ofile.close()  
  
  
